export { ViewSongs } from './ViewSongs';
import './viewsongs.css';
import 'assets/img/aerith.jpg';
import 'assets/img/ginyu.jpg';
import 'assets/img/gohan.jpg';
import 'assets/img/gohan2.jpg';
import 'assets/img/ichigo.jpg';
import 'assets/img/mario.png';
import 'assets/img/meteor.jpg';
import 'assets/img/mortal-kombat.jpg';
import 'assets/img/robin.jpg';
import 'assets/img/seer.jpg';
import 'assets/img/sonic.jpg';
import 'assets/img/sora.jpg';
import 'assets/img/spike-spiegel.jpg';
import 'assets/img/titan-dina.jpg';
import 'assets/img/vegeta.jpg';