export { ViewSongs } from './ViewSongs';
import './viewsongs.css';
import 'assets/img/dearly-beloved.jpg';
import 'assets/img/ff7-prelude.jpg';
import 'assets/img/mario-theme.jpg';
import 'assets/img/mario-theme2.jpg';
import 'assets/img/mario-theme3.jpg';
import 'assets/img/seer.png';
import 'assets/img/mario.png';
import 'assets/img/meteor.jpg';
import 'assets/img/sora.png';
import 'assets/img/mortal-kombat.png';
import 'assets/img/ginyu.png';
import 'assets/img/sonic.png';
import 'assets/img/armored-titan.png';