export const ICON_TYPES = {
  CLOSE: 'close',
  EDIT: 'edit',
  MINUS: 'minus',
  PLUS: 'plus',
  UNDO: 'undo'
};

export const MUSIC_ICON_TYPES = {
  WHOLE_NOTE: 'whole-note',
  HALF_NOTE: 'half-note',
  QUARTER_NOTE: 'quarter-note',
  EIGHTH_NOTE: 'eighth-note',
  SIXTEENTH_NOTE: 'sixteenth-note',
  STACCATO: 'staccato',
  DOTTED: 'dotted',
  ACCENT: 'accent',
  FERMATA: 'fermata',
  GRACE_NOTE: 'grace-note',
  NOTE_FLAT: 'note-flat',
  NOTE_NATURAL:'note-natural',
  NOTE_SHARP: 'note-sharp',
  ROLLED: 'rolled',
  TENUTO: 'tenuto',
  TRILL: 'trill',
  WHOLE_REST: 'whole-rest',
  HALF_REST: 'half-rest',
  QUARTER_REST: 'quarter-rest',
  EIGHTH_REST: 'eighth-rest',
  SIXTEENTH_REST: 'sixteenth-rest',
  REPEAT_START: 'repeat-start',
  REPEAT_END: 'repeat-end',
  MEASURE_END: 'measure-end',
  MEASURE_REMOVE: 'measure-remove',
  PEDAL_START: 'pedal-start',
  PEDAL_CONTINUE: 'pedal-continue',
  PEDAL_QUICK_RELEASE: 'pedal-quick-release',
  PEDAL_END: 'pedal-end',
  OTTAVA: 'ottava',
  OTTAVA_BASSA: 'ottava-bassa',
  PIANISSISSIMO: 'ppp',
  PIANISSIMO: 'pp',
  PIANO: 'p',
  MEZZOPIANO: 'mp',
  FORTEPIANO: 'fp',
  MEZZOFORTE: 'mf',
  FORTE: 'f',
  FORTISSIMO: 'ff',
  FORTISSISSIMO: 'fff',
  SFORZANDO: 'sfz',
  DIMINUENDO: 'dim.',
  RITARDANO: 'rit.',
  DECRESCENDO: 'decrescendo',
  CRESCENDO: 'crescendo',
  DECRESCENDO_TEXT: 'decresc.',
  CRESCENDO_TEXT: 'cresc.',
  LEGGIERO: 'leggiero',
  A_TEMPO: 'a tempo',
  RISOLUTO: 'risoluto',
  E: 'e',
  POCO_RITARDANO: 'poco rit.',
  DYNAMICS_REMOVE: 'dynamics-remove',
  PEDAL_REMOVE: 'pedal-remove'
};

export const ICON_SIZES = {
  EXTRA_SMALL: 'xs',
  SMALL: 's',
  MEDIUM: 'm',
  LARGE: 'l',
  EXTRA_LARGE: 'xl'
};